services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s

  backendVideojuegos:
    image: pabloalonso24/proyecto-mongo-tiendavideojuegos:latest
    container_name: backendVideojuegos
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data: