services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "until nc -z -v -w30 localhost 27017; do echo 'Waiting for MongoDB...'; sleep 5; done"]
      interval: 20s
      timeout: 10s
      retries: 5

  backendVideojuegos:
    image: pabloalonso24/proyecto-mongo-tiendavideojuegos:latest
    container_name: backendVideojuegos
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data: