services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backendVideojuegos:
    image: pabloalonso24/proyecto-mongo-tiendavideojuegos:latest
    container_name: backendVideojuegos
    ports:
      - "3000:3000"
    environment:
      - DB_USER=proyectomongodb74
      - DB_PASSWORD=zNXCNkjD1crJ45DK
      - DB_NAME=tienda
      - DB_CLUSTER=cluster0.gfwrr.mongodb.net

volumes:
  mongo_data: