name: Docker Build & Publish

on:
    push:
        branches:
            - master

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

            - name: Build Docker image
              run: docker build -t pabloalonso24/proyecto-mongo-tiendavideojuegos:${{ github.sha }} .

            - name: Tag Latest
              run: docker tag pabloalonso24/proyecto-mongo-tiendavideojuegos:${{ github.sha }} pabloalonso24/proyecto-mongo-tiendavideojuegos:latest

            - name: Push Docker Image
              run: |
                docker push pabloalonso24/proyecto-mongo-tiendavideojuegos:${{ github.sha }}
                docker push pabloalonso24/proyecto-mongo-tiendavideojuegos:latest